openapi: 3.0.0
info:
    version : '1.0.0'
    title: 'MY API'
    description : 'my API'
servers:
    - description : My API
      url: http://localhost:3000/
paths:
    /api/users:
        get:
            tags:
                - "User"
            summary: User API
            produces: 
                application/json
            parameters:
                []
            
            responses:
                '200':
                    description : add Result
                    scheam:
                        type : 'object'
                        $ref: '#/definitions/User'
                '400':
                    description : Result error
                    scheam:
                        type : integer
        post:
            tags:
                - "User"
            summary: User  post API
            parameters:
                - in: body
                  name: body
                  description: Updated user object
                  required: true
                  schema:
                    $ref: '#/definitions/User'

            responses:
                '200':
                    description : add Result
                    scheam:
                        type : integer
                '400':
                    description : Result error
                    scheam:
                        type : integer
definitions:
    User:
        type: object
        properties:
            id:
                type: integer
                format: int64
    
        xml:
          name: User