openapi: 3.0.0
info:
    version : '1.0.0'
    title: 'MY API'
    description : 'my API'
servers:
    - description : My API
      url: http://localhost:3000/
paths:
    /api/users:
        get:
            tags:
                - "User"
            summary: User API
            parameters:
                - name : one
                  in : query
                  description : 수정
                  required : true
                  schema:
                    type : integer
                - name : two
                  in : query
                  description : First Valus
                  required : true
                  schema:
                    type : integer
            responses:
                '200':
                    description : add Result
                    scheam:
                        type : integer
                '400':
                    description : Result error
                    scheam:
                        type : integer
        post:
            tags:
                - "User"
            summary: User  post API
            parameters:
                - in: body
                  name: body
                  description: Updated user object
                  required: true
                  schema:
                    $ref: '#/definitions/User'

            responses:
                '200':
                    description : add Result
                    scheam:
                        type : integer
                '400':
                    description : Result error
                    scheam:
                        type : integer
definitions:
    User:
        type: object
        properties:
            id:
                type: integer
                format: int64
            username:
                type: string
            firstName:
                type: string
            lastName:
                type: string
            email:
                type: string
            password:
                type: string
            userStatus:
                type: integer
                format: int32
                description: User Status
        xml:
          name: User